version: "3.9"

services:
  # MongoDB Service
  db_auth:
    image: mongo  # Chỉ định phiên bản cụ thể
    container_name: auth_database_mongo
    restart: always
    ports:
      - "27018:27017"  # Map cổng host 27018 tới cổng container 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: helu
      MONGO_INITDB_ROOT_PASSWORD: HeLu123
      MONGO_INITDB_DATABASE: Authenticator
      # Mongo sẽ luôn tạo sãn 1 volume anonymous sử dụng cho việc lắng nghe config có đường dãn là /data/configdb
    volumes:
      # Tạo volume mongo_data với tên là auth_mongo_data, đường dẫn là /data/db
      - mongo_data:/data/db
      # Định danh volume config là mongo_config, đường dẫn là /data/configdb
      - mongo_config:/data/configdb
      # Cơ chế Bind Mount
      # - ./database/database_auth_mongo:/data/db
      # - ./database/database_auth_mongo_config:/data/configdb 
    networks:
      - app-network

  # ASP.NET Core Backend API
  backend_auth:
    # build khi đang chạy local, về sau sẽ triển khai lấy từ image trên docker hub
    build:
      context: ../calendaroflife_backend_aspdotnet_authservice
      dockerfile: Dockerfile
    container_name: auth_service_dotnet
    ports:
      - "8080:8080"  # Map cổng host 8080 tới cổng container 8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDB__ConnectionString=mongodb://helu:HeLu123@db_auth:27017
      - MongoDB__Database=Authenticator
    depends_on:
      - db_auth
    networks:
      - app-network

  # React Frontend
  frontend_web:
    # build khi đang chạy local, về sau sẽ triển khai lấy từ image trên docker hub
    build:
      context: ../calendaroflife_frontend_react
      dockerfile: Dockerfile
    container_name: frontend_web_react
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_CLIENT_URL=/api/
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    depends_on:
      - backend_auth
    networks:
      - app-network

  # NGINX Gateway
  nginx:
    image: nginx:latest
    container_name: nginx_gateway
    ports:
      - "100:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend_web
      - backend_auth
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mongo_data:
    name: auth_mongo_data
  mongo_config:
    name: auth_mongo_config
networks:
  app-network:
    driver: bridge
    